name: Build and Release Mod

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod Version'
        required: true
        default: '1.1.0'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python 2.7 via Chocolatey
      run: |
        choco install python2 -y --no-progress

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil

    - name: Determine Version and Create build.json
      shell: pwsh
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ inputs.version }}"
        } else {
            $version = "${{ github.ref_name }}".TrimStart('v')
        }

        echo "PROJECT_VERSION=$version" >> $env:GITHUB_ENV
        Write-Host "Selected Version: $version"

        $jsonContent = @{
            version = 5
            software = @{
                animate = " "
                python = "C:/Python27/python.exe"
            }
            game = @{
                force = $false
                folder = "temp_game_folder"
                version = "2.1.0.2"
            }
            info = @{
                id = "me.under_pressure.calculationelo"
                name = "calculationelo"
                description = "calculation elo"
                version = $version
            }
        } | ConvertTo-Json -Depth 4
        $jsonContent | Out-File -FilePath build.json -Encoding UTF8

    - name: Create dummy game folders
      run: |
        New-Item -ItemType Directory -Force -Path "temp_game_folder/mods/2.1.0.0"

    - name: Run Build Script
      env:
        WOT_FOLDER: "temp_game_folder"
        WOT_VERSION: "2.1.0.2"
        
      run: python build.py --distribute

    - name: Upload to Release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ env.PROJECT_VERSION }}"
        artifacts: "build/*.wotmod"
        allowUpdates: true
        removeArtifacts: true
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
